#if UNITY_EDITOR
// UnityMapExporter.cs — unity-dev skill: the PREFERRED unitymap generator.
//
// scripts/build_unitymap.py reads the YAML from outside Unity and therefore
// guesses: it sees a serialized field name but not its declared type, and it
// cannot tell an unassigned reference from a field that was never serialized.
// This exporter runs inside the editor, so AssetDatabase and SerializedObject
// give it the real answers. Output is the same file, in the same format, so
// either generator can produce it; the stamp records which one did.
//
// Install: this file belongs at Assets/Editor/UnityMapExporter.cs. It is a .cs
// under Assets/, so it is a protected write — declare it in the preflight
// manifest like any other script, never copy it in with a shell command.
//
// Run: Tools > unity-dev > Export unitymap  (or Export unitymap + assetmap)
//
// Scene handling: the current scene setup is saved before and restored after,
// and modified scenes are offered for saving first. Nothing is left open.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace UnityDev
{
    public static class UnityMapExporter
    {
        private const int MaxObjectsPerAsset = 120;

        [MenuItem("Tools/unity-dev/Export unitymap")]
        public static void Export()
        {
            var projectRoot = Directory.GetParent(Application.dataPath).FullName;
            var dest = Path.Combine(projectRoot, ".claude", "unitymap.md");
            var keptNotes = ReadPreservedNotes(dest);

            var findings = new SortedSet<string>();
            var scriptIndex = new SortedDictionary<string, string>();
            var body = new StringBuilder();
            int sceneCount = 0, prefabCount = 0;

            var setup = EditorSceneManager.GetSceneManagerSetup();
            if (!EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
            {
                Debug.LogWarning("[unity-dev] Export cancelled: unsaved scene changes.");
                return;
            }

            try
            {
                foreach (var path in FindAssets("t:Scene").Where(p => p.EndsWith(".unity", StringComparison.Ordinal)))
                {
                    sceneCount++;
                    var scene = EditorSceneManager.OpenScene(path, OpenSceneMode.Single);
                    WriteAssetSection(body, "SCENE", path, scene.GetRootGameObjects(), null, findings, scriptIndex);
                }

                foreach (var path in FindAssets("t:Prefab"))
                {
                    prefabCount++;
                    var root = AssetDatabase.LoadAssetAtPath<GameObject>(path);
                    if (root == null) continue;
                    WriteAssetSection(body, "PREFAB", path, new[] { root }, VariantOf(root), findings, scriptIndex);
                }
            }
            finally
            {
                if (setup != null && setup.Length > 0) EditorSceneManager.RestoreSceneManagerSetup(setup);
            }

            var missing = findings.Count(f => f.StartsWith("MISSING SCRIPT", StringComparison.Ordinal));
            var unassigned = findings.Count(f => f.StartsWith("UNASSIGNED", StringComparison.Ordinal));
            var status = missing == 0 ? "OK" : "DEGRADED " + missing + " missing-script";

            var sb = new StringBuilder();
            sb.Append("<!-- stamp: ").Append(DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mmZ"))
              .Append(" source-sig:editor-export scenes:").Append(sceneCount)
              .Append(" prefabs:").Append(prefabCount)
              .Append(" generator:unity-editor status: ").Append(status).AppendLine(" -->");
            sb.AppendLine("# unitymap — scene and prefab structure");
            sb.AppendLine();
            sb.AppendLine("Read this instead of opening a `.unity`/`.prefab` file. Tree indentation is");
            sb.AppendLine("the GameObject hierarchy; `[...]` lists the components on the object;");
            sb.AppendLine("`refs:` lists serialized reference slots with their declared type and whether");
            sb.AppendLine("the Inspector has something in them. `*` marks a prefab instance.");
            sb.AppendLine();
            sb.AppendLine("Generated by Assets/Editor/UnityMapExporter.cs (Tools > unity-dev > Export");
            sb.AppendLine("unitymap), which has real type information. `source-sig:editor-export` means");
            sb.AppendLine("the python fallback cannot judge this file's freshness — re-export after");
            sb.AppendLine("editor work rather than trusting the age of the stamp.");
            sb.AppendLine();

            if (findings.Count > 0)
            {
                sb.AppendLine("## Findings");
                foreach (var f in findings.Take(60)) sb.Append("- ").AppendLine(f);
                if (findings.Count > 60) sb.Append("- ... ").Append(findings.Count - 60).AppendLine(" more");
                sb.AppendLine();
            }

            sb.Append(body);

            if (scriptIndex.Count > 0)
            {
                sb.AppendLine("## Script index — component name -> codemap path");
                sb.AppendLine();
                foreach (var kv in scriptIndex) sb.Append("- ").Append(kv.Key).Append(" | ").AppendLine(kv.Value);
                sb.AppendLine();
            }
            if (keptNotes.Count > 0)
            {
                sb.AppendLine("## Preserved notes");
                foreach (var n in keptNotes) sb.AppendLine(n);
                sb.AppendLine();
            }

            Directory.CreateDirectory(Path.GetDirectoryName(dest));
            File.WriteAllText(dest, sb.ToString().TrimEnd() + "\n");
            Debug.Log(string.Format(
                "[unity-dev] unitymap exported: {0} scene(s), {1} prefab(s), {2} missing script(s), {3} unassigned slot(s) -> .claude/unitymap.md",
                sceneCount, prefabCount, missing, unassigned));
        }

        [MenuItem("Tools/unity-dev/Export unitymap + assetmap")]
        public static void ExportBoth()
        {
            Export();
            AssetMap();
        }

        // ------------------------------------------------------------ helpers

        private static IEnumerable<string> FindAssets(string filter)
        {
            return AssetDatabase.FindAssets(filter, new[] { "Assets" })
                .Select(AssetDatabase.GUIDToAssetPath)
                .Distinct()
                .OrderBy(p => p, StringComparer.Ordinal);
        }

        private static List<string> ReadPreservedNotes(string dest)
        {
            var notes = new List<string>();
            if (File.Exists(dest))
                notes.AddRange(File.ReadAllLines(dest).Where(l => l.StartsWith(">> note:", StringComparison.Ordinal)));
            return notes;
        }

        private static string VariantOf(GameObject prefabRoot)
        {
            if (PrefabUtility.GetPrefabAssetType(prefabRoot) != PrefabAssetType.Variant) return null;
            var basePrefab = PrefabUtility.GetCorrespondingObjectFromSource(prefabRoot);
            return basePrefab == null ? null : AssetDatabase.GetAssetPath(basePrefab);
        }

        private static void WriteAssetSection(StringBuilder body, string kind, string path,
            GameObject[] roots, string variantOf, SortedSet<string> findings,
            SortedDictionary<string, string> scriptIndex)
        {
            var lines = new List<string>();
            var budget = MaxObjectsPerAsset;
            var total = 0;
            foreach (var root in roots) Walk(root, 0, path, lines, ref budget, ref total, findings, scriptIndex);

            body.Append("## ").Append(kind).Append(' ').Append(path);
            if (!string.IsNullOrEmpty(variantOf)) body.Append("   variant-of: ").Append(variantOf);
            body.Append("   (").Append(total).AppendLine(" object(s))");
            if (lines.Count == 0) body.AppendLine("- (empty)");
            foreach (var l in lines) body.AppendLine(l);
            if (total > MaxObjectsPerAsset)
                body.Append("- ... ").Append(total - MaxObjectsPerAsset).AppendLine(" more object(s) not listed");
            body.AppendLine();
        }

        private static void Walk(GameObject go, int depth, string assetPath, List<string> lines,
            ref int budget, ref int total, SortedSet<string> findings,
            SortedDictionary<string, string> scriptIndex)
        {
            total++;
            if (budget <= 0)
            {
                for (int i = 0; i < go.transform.childCount; i++)
                    Walk(go.transform.GetChild(i).gameObject, depth + 1, assetPath, lines, ref budget, ref total, findings, scriptIndex);
                return;
            }
            budget--;

            var comps = new List<string>();
            var refBits = new List<string>();
            foreach (var c in go.GetComponents<Component>())
            {
                if (c == null)
                {
                    comps.Add("MISSING SCRIPT");
                    findings.Add("MISSING SCRIPT | " + assetPath + " | " + go.name);
                    continue;
                }
                var label = c.GetType().Name;
                comps.Add(label);

                var mb = c as MonoBehaviour;
                if (mb != null)
                {
                    var ms = MonoScript.FromMonoBehaviour(mb);
                    if (ms != null)
                    {
                        var p = AssetDatabase.GetAssetPath(ms);
                        if (!string.IsNullOrEmpty(p)) scriptIndex[label] = p;
                    }
                    CollectRefs(mb, label, go, assetPath, refBits, findings);
                }
            }

            var prefabTag = PrefabUtility.IsAnyPrefabInstanceRoot(go)
                ? "* " + go.name + "  (prefab instance of " +
                  AssetDatabase.GetAssetPath(PrefabUtility.GetCorrespondingObjectFromSource(go)) + ")"
                : go.name;
            var inactive = go.activeSelf ? "" : " [inactive]";
            var refs = refBits.Count > 0 ? "  refs: " + string.Join(", ", refBits.ToArray()) : "";
            lines.Add(new string(' ', depth * 2) + "- " + prefabTag + inactive +
                      "  [" + (comps.Count > 0 ? string.Join(", ", comps.ToArray()) : "-") + "]" + refs);

            for (int i = 0; i < go.transform.childCount; i++)
                Walk(go.transform.GetChild(i).gameObject, depth + 1, assetPath, lines, ref budget, ref total, findings, scriptIndex);
        }

        private static void CollectRefs(MonoBehaviour mb, string label, GameObject go, string assetPath,
            List<string> refBits, SortedSet<string> findings)
        {
            var so = new SerializedObject(mb);
            var it = so.GetIterator();
            var enterChildren = true;
            while (it.NextVisible(enterChildren))
            {
                enterChildren = false;
                if (it.propertyType != SerializedPropertyType.ObjectReference) continue;
                if (it.name == "m_Script") continue;
                var typeName = string.IsNullOrEmpty(it.type) ? "Object" : it.type.Replace("PPtr<$", "").TrimEnd('>');
                if (it.objectReferenceValue == null)
                {
                    refBits.Add(it.name + ":" + typeName + "=NULL");
                    findings.Add("UNASSIGNED | " + assetPath + " | " + go.name + "." + label + "." + it.name);
                }
                else
                {
                    refBits.Add(it.name + ":" + typeName + "=set");
                }
            }
        }

        // ------------------------------------------------------------ assetmap

        [MenuItem("Tools/unity-dev/Export assetmap")]
        public static void AssetMap()
        {
            var projectRoot = Directory.GetParent(Application.dataPath).FullName;
            var dest = Path.Combine(projectRoot, ".claude", "assetmap.md");
            var keptNotes = new List<string>();
            if (File.Exists(dest))
                keptNotes.AddRange(File.ReadAllLines(dest).Where(l => l.StartsWith(">> note:", StringComparison.Ordinal)));

            var assets = new List<string>();
            foreach (var p in FindAssets("t:ScriptableObject"))
            {
                var obj = AssetDatabase.LoadAssetAtPath<ScriptableObject>(p);
                if (obj == null) continue;
                var ms = MonoScript.FromScriptableObject(obj);
                var scriptPath = ms == null ? "?" : AssetDatabase.GetAssetPath(ms);
                assets.Add("- " + p + " | type: " + obj.GetType().Name + " | script: " + scriptPath);
            }

            var prefabs = new List<string>();
            foreach (var p in FindAssets("t:Prefab"))
            {
                var root = AssetDatabase.LoadAssetAtPath<GameObject>(p);
                if (root == null) continue;
                var v = VariantOf(root) ?? "-";
                var scripts = root.GetComponentsInChildren<MonoBehaviour>(true)
                    .Where(m => m != null).Select(m => m.GetType().Name).Distinct().Take(8).ToArray();
                prefabs.Add("- " + p + " | variant-of: " + v + " | scripts: " +
                            (scripts.Length > 0 ? string.Join(", ", scripts) : "-"));
            }

            var scenes = FindAssets("t:Scene").Where(p => p.EndsWith(".unity", StringComparison.Ordinal))
                .Select(p => "- " + p).ToList();

            var asmdefs = AssetDatabase.FindAssets("t:AssemblyDefinitionAsset", new[] { "Assets" })
                .Select(AssetDatabase.GUIDToAssetPath).OrderBy(p => p, StringComparer.Ordinal)
                .Select(p => "- " + p + " | covers: " + Path.GetDirectoryName(p).Replace('\\', '/') + "/**").ToList();

            var loadSurface = AssetDatabase.GetAllAssetPaths()
                .Where(p => p.StartsWith("Assets/", StringComparison.Ordinal) &&
                            (p.Contains("/Resources/") || p.Contains("/StreamingAssets/")))
                .OrderBy(p => p, StringComparer.Ordinal)
                .Select(p => "- " + p + " | loaded by string at runtime; ships in every build").ToList();

            var sb = new StringBuilder();
            sb.Append("<!-- stamp: ").Append(DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mmZ"))
              .Append(" source-sig:editor-export assets:").Append(assets.Count)
              .Append(" prefabs:").Append(prefabs.Count).Append(" scenes:").Append(scenes.Count)
              .Append(" asmdefs:").Append(asmdefs.Count).AppendLine(" -->");
            sb.AppendLine("# assetmap — asset inventory (data, prefabs, load surface, assemblies)");
            sb.AppendLine();
            sb.AppendLine("Generated by Tools > unity-dev > Export assetmap (real types from AssetDatabase).");
            sb.AppendLine();
            Section(sb, "Assemblies (.asmdef) — the real compile boundary", asmdefs);
            Section(sb, "ScriptableObject assets", assets);
            Section(sb, "Prefabs", prefabs);
            Section(sb, "Scenes", scenes);
            Section(sb, "Runtime load surface", loadSurface);
            if (keptNotes.Count > 0)
            {
                sb.AppendLine("## Preserved notes");
                sb.AppendLine();
                foreach (var n in keptNotes) sb.AppendLine(n);
                sb.AppendLine();
            }

            Directory.CreateDirectory(Path.GetDirectoryName(dest));
            File.WriteAllText(dest, sb.ToString().TrimEnd() + "\n"); Debug.Log(string.Format("[unity-dev] assetmap exported: {0} SO asset(s), {1} prefab(s) -> .claude/assetmap.md",
                 assets.Count, prefabs.Count));
        }

        private static void Section(StringBuilder sb, string title, List<string> rows)
        {
            sb.Append("## ").AppendLine(title);
            sb.AppendLine();
            if (rows.Count == 0) sb.AppendLine("- (none)");
            else foreach (var r in rows.Take(200)) sb.AppendLine(r);
            if (rows.Count > 200) sb.Append("- ... ").Append(rows.Count - 200).AppendLine(" more");
            sb.AppendLine();
        }
    }
}
#endif
